(defun palindrome (input)
	(if (equal input (reverse input))
		(format t "~a is a palindrome~%" input)
		(format t "~a is not a palindrome~%" input)
	)
	; or you can use dolist with (append)
)

(palindrome '(a b c ) )
(palindrome '(m a d a m))
(palindrome '(cat dog))
(palindrome '())
(palindrome '(cat dog bird bird dog cat))
